server:
  port: 9006
spring:
  application:
    name: sso-server
### freemarker
  freemarker:
    request-context-attribute: request
    cache: false
### resource (default: /**  + classpath:/static/ )
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true