spring:
  application:
    name: main-service-client
  zipkin:
    base-url: http://localhost:9009
server:
  port: 9003
feign:
  hystrix:
    enabled: true
ribbon:
  eureka:
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/